name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    #- name: Build the application
    #  run: go build -v -o bin/scrumpoke ./cmd/scrumpoke
    - name: Run tests
      run: |
        export GOPATH="$HOME/go/"
        export PATH=$PATH:$GOPATH/bin
        go install github.com/jstemmer/go-junit-report@latest
        go test -v ./... | go-junit-report -set-exit-code > report.xml
    - name: Test Summary
      uses: test-summary/action@v1
      with:
        paths: |
          report.xml

